version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - mkdir -p build-output
      - cp -r build/* build-output/
      - cp server.js build-output/
      - cp package.json build-output/
artifacts:
  base-directory: build-output
  files:
    - '**/*'